---
name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
env:
  CARGO_TERM_COLOR: always

jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create an incremental release
      id: tag_step
      uses: aurestic/incrementarl-create-release@master
      with:
        flag_branch: true
        # message: Bump version
        prev_tag: 'v'
        update_odoo_module_version: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create auto release
      id: auto_step
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: ${{ steps.tag_step.outputs.new_tag }}
        prerelease: false
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
    outputs:
      upload_url: ${{ steps.auto_step.outputs.upload_url }}

  uploading_files:
    name: Building and uploading files
    needs: auto_release
    strategy:
      matrix:
        config:
        - os:
            name: ubuntu-latest
            short_name: "linux"
            built_file: "target/release/rust-render"
        - os: 
            name: macos-latest
            short_name: "mac"
            built_file: "target/release/rust-render"
        - os:
            name: windows-latest
            short_name: "win.exe"
            built_file: "target/release/rust-render.exe"
    runs-on: ${{ matrix.config.os.name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        upload_url: ${{ needs.auto_release.outputs.upload_url }}
        asset_name: rust-render-${{ matrix.config.os.short_name }}
        asset_path: ${{ matrix.config.os.built_file }}
        asset_content_type: application/octet-stream
