---
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  automatic_release:
    name: Automatic Release
    runs-on: "${{ matrix.config.os }}"
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            built_file: "target/release/rust-render"
          - os: macos-latest
            built_file: "target/release/rust-render"
          - os: windows-latest
            built_file: "target/release/rust-render.exe"

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release assets
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "latest"
        prerelease: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: "${{ matrix.config.os.built_file }}"
        upload_url: "https://github.com/janix/rust-render/archive/refs/tags/${{ matrix.config.os }}"
