---
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
    - name: Create auto release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "latest"
        prerelease: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"

  uploading_files:
    name: Building and uploading files
    strategy:
      matrix:
        config:
        - os: ubuntu-latest
          short_name: "linux"
          built_file: "target/release/rust-render"
        - os: macos-latest
          short_name: "mac"
          built_file: "target/release/rust-render"
        - os: windows-latest
          short_name: "win"
          built_file: "target/release/rust-render.exe"
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Check matrix variables
      run: echo ${{ matrix.config.os }} ${{ matrix.config.os.built_file }} ${{ matrix.config.os.short_name }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        upload_url: ${{ job.auto_release.outputs.upload_url }}
        asset_name: rust-render-${{ matrix.config.os.short_name }}
        asset_path: ${{ matrix.config.os.built_file }}
        asset_content_type: application/octet-stream
