name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release_assets:
    name: Release assets
    needs: create_release # we need to know the upload URL
    runs-on: ${{ matrix.config.os }} # we run many different builds
    strategy:
      # just an example matrix
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        # This is how it will be named on the release page. Put hatever name
        # you like, remember that they need to be different for each platform.
        # You can choose any build matrix parameters. For Rust I use the
        # target triple.
        asset_name: rust-render-${{ matrix.config.os }}
        # The path to the file you want to upload.
        asset_path: target/release/rust-render
        # probably you will need to change it, but most likely you are
        # uploading a binary file
        asset_content_type: application/octet-stream
        