---
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  automatic_release:
    name: Automatic Release
    runs-on: ${{ matrix.os }}
    strategy:  
      matrix:
        config:
        - os: ubuntu-latest

    steps:
    - name: Check matrix variables
      run: echo ${{ matrix.os }} ${{ matrix.build_type }}
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Running automatic release
      id: auto_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "latest"
        prerelease: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: "${{ matrix.config.os.parameters.built_file }}"

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        upload_url: ${{ steps.auto_release.outputs.upload_url }}
        asset_name: rust-render-${{ matrix.config.os.parameters.short_name }}
        asset_path: ${{ matrix.config.os.parameters.built_file }}
        asset_content_type: application/octet-stream
